on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 */1 * *'


env:
  password: ${{ secrets.password }}
  keys_password: ${{ secrets.password }}
  drive_copy: ${{ secrets.drive_copy }}
  drive_trash: ${{ secrets.drive_trash }}


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/go1gl2-dr3ve@cron
        with:
          token: ${{ secrets.token }}
